[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install --omit=dev"

[deploy]
startCommand = "cd backend && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixpkgsVersion = "22.11"
